"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
var sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
    // But you can create a sidebar manually
    /*
    tutorialSidebar: [
      'intro',
      'hello',
      {
        type: 'category',
        label: 'Tutorial',
        items: ['tutorial-basics/create-a-document'],
      },
    ],
     */
    docsSidebar: [
        // This is the structure you requested
        {
            type: 'category',
            label: 'Agentic AI in Banking', // This is the visible text in the sidebar
            link: {
                type: 'doc',
                id: 'index', // Links to the 'docs/category.md' file's ID
            },
            items: [
                'banking-reimagined-through-agentic-ai',
                'balancing-autonomy-and-agency',
                'the-ai-use-case-canvas',
                'enabling-agentic-ai-through-well-defined-api-contracts',
                'selecting-the-right-ai-model',
                'high-impact-use-cases',
                'building-enterprise-ai-agents'
            ],
        },
    ]
};
exports.default = sidebars;
